@rootURL = http://localhost:5284

GET {{rootURL}}/weatherforecast/
Accept: application/json

###

GET {{rootURL}}/api/product
Accept: application/json

###

GET {{rootURL}}/api/order
Accept: application/json

###


POST {{rootURL}}/api/product/create-product
Content-Type: application/json
{
  "name": "Tecno Spark 20 Pro - 6.78\" 256GB/8+8GB 4G LTE, 5000mAh - Sunset",
  "description": "Introducing Spark 20, the ultimate smartphone for the energy vibe.",
  "price": "309999"
}

###

POST {{rootURL}}/api/order/create-order
Content-Type: application/json
{
  "name": "1415646272",
  "products": [
    { "productId": "1", "quantity": "5" },
    { "productId": "6", "quantity": "4" }
  ]
}

###