@rootURL = http://localhost:5284

GET {{rootURL}}/weatherforecast/
Accept: application/json

###

GET {{rootURL}}/api/product
Accept: application/json

###

GET {{rootURL}}/api/order
Accept: application/json

###


POST {{rootURL}}/api/product/create-product
Content-Type: application/json
{
  "name": "Pack Of 2 Plain Sleeveless Hooded T Shirt- Black & Grey",
  "description": "Enjoy this DANAMI's  quality and stylish sleeveless t shirts with hood for comfort and causal outing and jogging. This 2 in one is made of fine cotton material. Please check DANAMI for more designs, colours, and styles.",
  "price": "15900"
}

###

POST {{rootURL}}/api/order/create-order
Content-Type: application/json
{
  "name": "1923271452",
  "quantity": "3",
  "productId": "4"
}

###